import 'dart:ui';

import 'package:flutix/bloc/blocs.dart';
import 'package:flutix/models/models.dart';
import 'package:flutix/services/services.dart';
import 'package:flutix/extensions/extensions.dart';
import 'package:flutix/shared/shared.dart';
import 'package:flutix/ui/widgets/widgets.dart';
import 'package:another_flushbar/flushbar.dart';
import 'package:email_validator/email_validator.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:provider/provider.dart';
import 'package:random_string/random_string.dart';

part 'splash_page.dart';
part 'main_page.dart';
part 'signin_page.dart';
part 'signup_page.dart';
part 'account_confirmation_page.dart';
part 'preference_page.dart';
part 'wrapper.dart';
part 'movie_page.dart';
part 'movie_detail_page.dart';
part 'coming_movie_detail_page.dart';
part 'select_schedule_page.dart';
part 'select_seat_page.dart';
part 'checkout_page.dart';